services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - 16379:6379
    volumes:
      - valkey:/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  valkey:
  redis:
